---
- name: Preparing installation to deploy cluster
  hosts: localhost
  gather_facts: false
  vars_files: vars.yml

  tasks:
   - name: Creating folder via spec module
     ansible.builtin.file:
      path: /test/testdir123
      state: directory
      mode: '0755'

   - name: test
     ansible.builtin.shell: date

   - name: Creating folder via spec module
     ansible.builtin.file:
      path: /test/testdir123
      state: directory
      mode: '0755'

   - name: test
     ansible.builtin.shell: date
